services:
    # ---------- FRONTEND ----------
    frontend:
        build: ./frontend/table_booking
        container_name: frontend
        restart: always
        networks:
            - table_booking

    # ---------- USER SERVICE ----------
    auth-service:
        build: ./backend/apps/auth_service
        volumes:
            - ./backend/apps/auth_service:/app
            - ./shared:/shared
        container_name: auth-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- CATEGORY SERVICE ----------
    billing-service:
        build: ./backend/apps/billing_service
        volumes:
            - ./backend/apps/billing_service:/app
            - ./shared:/shared
        container_name: billing-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- PRODUCT SERVICE ----------
    menu-service:
        build: ./backend/apps/menu_service
        volumes:
            - ./backend/apps/menu_service:/app
            - ./shared:/shared
        container_name: menu-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- ORDER SERVICE ----------
    notification-service:
        build: ./backend/apps/notification_service
        volumes:
            - ./backend/apps/notification_service:/app
            - ./shared:/shared
        container_name: notification-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- PAYMENT SERVICE ----------
    order-service:
        build: ./backend/apps/order_service
        volumes:
            - ./backend/apps/order_service:/app
            - ./shared:/shared
        container_name: order-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- CART SERVICE ----------
    table-service:
        build: ./backend/apps/table_service
        volumes:
            - ./backend/apps/table_service:/app
            - ./shared:/shared
        container_name: table-service
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - .env
        environment:
            PYTHONPATH: '/shared'
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            - postgres
            - redis
            - rabbitmq
        networks:
            - table_booking

    # ---------- DATABASE ----------
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - table_booking
        ports:
            - '5432:5432'
        healthcheck:
            test:
                [
                    'CMD-SHELL',
                    'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}',
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    # ---------- CACHE ----------
    redis:
        image: redis:7-alpine
        container_name: redis
        restart: always
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - '6379:6379'
        networks:
            - table_booking
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5

    # ---------- MESSAGE QUEUE ----------
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - table_booking
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ['CMD', 'rabbitmqctl', 'status']
            interval: 10s
            timeout: 5s
            retries: 5

    # ---------- REVERSE PROXY ----------
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - frontend
            - auth-service
            - table-service
            - menu-service
            - order-service
            - billing-service
        networks:
            - table_booking

networks:
    table_booking:

volumes:
    postgres_data:
    redis_data:
    rabbitmq_data:
