services:
    # ---------- FRONTEND ----------
    frontend:
        build: ./frontend/table_booking
        volumes:
            - ./frontend/table_booking:/app
            - /app/node_modules
        ports:
            - '5173:5173'
        depends_on:
            - nginx
        networks:
            - table_booking

    # ---------- AUTH SERVICE ----------
    auth-service:
        build: ./backend/app/auth-service
        container_name: auth-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/auth-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/1
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- BILLING SERVICE ----------
    billing-service:
        build: ./backend/app/billing-service
        container_name: billing-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/billing-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/2
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- MENU SERVICE ----------
    menu-service:
        build: ./backend/app/menu-service
        container_name: menu-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/menu-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/3
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- NOTIFICATION SERVICE ----------
    notification-service:
        build: ./backend/app/notification-service
        container_name: notification-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/notification-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/6
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- ORDER SERVICE ----------
    order-service:
        build: ./backend/app/order-service
        container_name: order-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/order-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/4
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- TABLE SERVICE ----------
    table-service:
        build: ./backend/app/table-service
        container_name: table-service
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        volumes:
            - ./backend/app/table-service:/app
            - ./shared:/shared
        env_file: .env
        environment:
            PYTHONPATH: /shared:/app
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432
            REDIS_URL: redis://redis:6379/5
            RABBITMQ_URL: amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        networks:
            - table_booking

    # ---------- POSTGRES ----------
    postgres:
        image: postgres:17
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - table_booking

    # ---------- REDIS ----------
    redis:
        image: redis:7-alpine
        container_name: redis
        command: ['redis-server', '--appendonly', 'yes']
        volumes:
            - redis_data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5
        networks:
            - table_booking

    # ---------- RABBITMQ ----------
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
        ports:
            - '15672:15672'
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        healthcheck:
            test: ['CMD', 'rabbitmqctl', 'status']
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - table_booking

    # ---------- NGINX ----------
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - auth-service
            - table-service
            - menu-service
            - order-service
            - billing-service
            - notification-service
        networks:
            - table_booking

networks:
    table_booking:

volumes:
    postgres_data:
    redis_data:
    rabbitmq_data:
